engines:
  bandit:
    enabled: true
    exclude_paths:
      - tests/*
    config:
      ignore:
        - B601  # generic subprocess use warning
        - B602  # subprocess call with non-literal argument
        - B603  # subprocess_without_shell_equals_true or similar
