repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Check the latest version
    hooks:
      - id: trailing-whitespace
        exclude: "src/access_moppy/cmor_tables"
      - id: end-of-file-fixer
        exclude: "src/access_moppy/cmor_tables"
      - id: check-yaml
        exclude: "^(src/access_moppy/cmor_tables|.conda/meta.yaml)$"
      #- id: check-added-large-files
      - id: debug-statements  # Detects print() and pdb in code

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4  # Use a specific version
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: "_version.py"
      - id: ruff-format
        exclude: "_version.py"
