# === General input/output paths
input_folder: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/JuneSpinUp-JuneSpinUp-bfaa9c5b
output_folder: /scratch/tm70/rb5533/mopper_output
drs_root: /scratch/tm70/rb5533/mopper_output/CMIP

# === CMIP6 metadata
experiment_id: piControl
source_id: ACCESS-ESM1-5
variant_label: r1i1p1f1
grid_label: gn
activity_id: CMIP

# === List of variables to CMORise (table.variable)
variables:
  - Amon.pr
  - Omon.tos
  - Amon.tauu
  - Amon.ts
  - Omon.zos
  - Amon.hfss
  - Amon.rlds
  - Amon.rlus
  - Amon.rsds
  - Amon.rsus

file_patterns:
  Amon.pr: "output[0-4][0-9][0-9]/atmosphere/netCDF/*mon.ncatmosphere/*pr*_mon.nc"
  Omon.tos: "output[0-4][0-9][0-9]/ocean/ocean-2d-surface_temp-1monthly-mean*.nc"
  Amon.tauu: "output[0-4][0-9][0-9]/atmosphere/netCDF/*mon.nc"
  Amon.ts: "output[0-4][0-9][0-9]/atmosphere/netCDF/*mon.nc"
  Omon.zos: "output[0-4][0-9][0-9]/ocean/ocean-2d-sea_level-1monthly-mean*.nc"
  Amon.hfss: "output[0-4][0-9][0-9]/atmosphere/netCDF/*mon.nc"
  Amon.rlds: "output[0-4][0-9][0-9]/atmosphere/netCDF/*mon.nc"
  Amon.rlus: "output[0-4][0-9][0-9][0-9]/atmosphere/netCDF/*mon.nc"
  Amon.rsds: "output[0-4][0-9][0-9]/atmosphere/netCDF/*mon.nc"
  Amon.rsus: "output[0-4][0-9][0-9][0-9]/atmosphere/netCDF/*mon.nc"

# === Job submission settings
cpus_per_node: 14
mem: 32GB
walltime: 01:00:00
storage: gdata/p73+gdata/tm70+scratch/tm70
nodes_per_block: 2
init_blocks: 2
max_blocks: 20
queue: normal
scheduler_options: "#PBS -P tm70"
worker_init: "source /g/data/tm70/rb5533/miniforge3/bin/activate && conda activate esmvaltool_dev"
