{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set version = data.get('version') %}

package:
    name: access-mopper
    version: "{{ version }}"

source:
  git_url: https://github.com/ACCESS-NRI/ACCESS-MOPPeR.git
  git_tag: "{{ version }}"

build:
    noarch: python
    number: 0
    script: "{{ PYTHON }} -m pip install . -vv"

requirements:
    host:
        - python
        - pip
        - versioneer
    run:
        - python >=3.11
        - xarray
        - cmor
        - numpy
        - dask
        - pyyaml
        - cftime

about:
    home: https://github.com/ACCESS-Community-Hub/ACCESS-MOPPeR
    license: Apache Software
    license_family: APACHE
    summary: 'ACCESS-MOPPeR post-process ACCESS raw model output using CMOR and pre-defined data standards'

extra:
    recipe-maintainers:
        - rbeucher
