{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set version = data.get('version') %}

package:
    name: access-moppy
    version: "{{ version }}"

source:
    url: "https://files.pythonhosted.org/packages/source/a/access_moppy/access_moppy-{{ version }}.tar.gz"

build:
    noarch: python
    number: 0
    script: "{{ PYTHON }} -m pip install . -vv"

requirements:
    host:
        - python >= 3.11
        - pip
    run:
        - python >=3.11
        - xarray
        - numpy
        - dask
        - pyyaml
        - cftime

about:
    home: https://github.com/ACCESS-NRI/ACCESS-MOPPy
    license: Apache-2.0
    summary: 'ACCESS-MOPPy post-process ACCESS raw model output using CMOR and pre-defined data standards'

extra:
    recipe-maintainers:
        - rbeucher
