name: access-nri-mopper-test
channels:
  - conda-forge
  - accessnri
  - defaults
dependencies:
  - python==3.13
  - xarray
  - cmor
  - numpy
  - dask
  - pyyaml
  - cftime
  - pip
  - pip:
    - codecov
    - pytest-cov
