"""Render the QC physical-range rules into a documentation table.

The rules ACCESS-MOPPy applies to every CMORised file live in
``src/access_moppy/resources/qc/cmip7_ranges.yml``.  Rather than restating a
handful of them by hand — and letting the documentation drift the moment a
bound is retuned — the whole set is rendered into
``docs/source/_generated/qc_ranges_table.rst`` at build time and included by
``docs/source/reference/qc_ranges.rst``.

Called from ``docs/source/conf.py``; the fragment it writes is a generated
artefact and is not committed (see ``.gitignore``).  It can also be run
directly while editing::

    python docs/qc_ranges.py [output_dir]

The YAML is read straight from the source tree rather than through
``import access_moppy``, because importing the package runs
``_config.load_moppy_config()``, which prompts on stdin when
``~/.moppy/user.yml`` is missing and would hang a Read the Docs build.
"""

from __future__ import annotations

import html
import sys
from pathlib import Path
from typing import Any

import yaml

DOCS_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = DOCS_DIR.parent
RULES_FILE = (
    PROJECT_ROOT / "src" / "access_moppy" / "resources" / "qc" / "cmip7_ranges.yml"
)

DEFAULT_OUT_DIR = DOCS_DIR / "source" / "_generated"
OUT_NAME = "qc_ranges_table.rst"


def _format_number(value: Any) -> str:
    """Render a bound the way a reader would write it, not as a float repr."""
    number = float(value)
    if number == int(number) and abs(number) < 1e15:
        return str(int(number))
    return f"{number:g}"


def _overrides(variable_rules: dict[str, Any]) -> str:
    """Summarise the experiment-specific overrides for one variable."""
    experiments = variable_rules.get("experiments") or {}
    parts = []
    for experiment_id in sorted(experiments):
        rule = experiments[experiment_id] or {}
        bounds = []
        if "min" in rule:
            bounds.append(f"min {_format_number(rule['min'])}")
        if "max" in rule:
            bounds.append(f"max {_format_number(rule['max'])}")
        parts.append(f"{experiment_id}: {', '.join(bounds) if bounds else 'default'}")
    return "; ".join(parts)


def load_rules(rules_file: Path | str = RULES_FILE) -> dict[str, Any]:
    """Return the ``variables`` section of the QC rules file."""
    with open(rules_file, "r", encoding="utf-8") as handle:
        config = yaml.safe_load(handle) or {}
    return config.get("variables", {})


def render_table(rules: dict[str, Any]) -> str:
    """Render the rules as an HTML table wrapped in a ``raw`` directive."""
    rows = []
    for variable_id in sorted(rules):
        variable_rules = rules[variable_id] or {}
        default = variable_rules.get("default") or {}
        if "min" not in default or "max" not in default:
            continue
        rows.append(
            "        <tr>"
            f'<td class="moppy-var">{html.escape(variable_id)}</td>'
            f"<td>{html.escape(str(variable_rules.get('units') or ''))}</td>"
            f'<td class="moppy-num">{_format_number(default["min"])}</td>'
            f'<td class="moppy-num">{_format_number(default["max"])}</td>'
            f"<td>{html.escape(_overrides(variable_rules))}</td>"
            "</tr>"
        )

    header = [
        ".. This file is generated by docs/qc_ranges.py — do not edit.",
        "",
        ".. raw:: html",
        "",
        '   <div class="moppy-ranges-container">',
        '     <div class="moppy-ranges-filter">',
        '       <input type="search" placeholder="Filter by variable, unit or experiment…"',
        '              aria-label="Filter the physical-range table">',
        '       <span class="moppy-ranges-count"></span>',
        "     </div>",
        '     <div class="moppy-ranges-wrapper">',
        '     <table class="moppy-ranges">',
        "       <thead><tr>",
        "         <th>Variable</th><th>Units</th><th>Default min</th>",
        "         <th>Default max</th><th>Experiment overrides</th>",
        "       </tr></thead>",
        "       <tbody>",
    ]
    footer = [
        "       </tbody>",
        "     </table>",
        "     </div>",
        "   </div>",
        "",
        f".. note:: {len(rows)} variables carry a physical-range rule.",
        "",
    ]
    return "\n".join(header + rows + footer)


def generate(out_dir: Path | str = DEFAULT_OUT_DIR) -> Path:
    """Write the rendered range table into ``out_dir``."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / OUT_NAME
    target.write_text(render_table(load_rules()), encoding="utf-8")
    return target


if __name__ == "__main__":
    destination = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUT_DIR
    print(f"wrote {generate(destination)}")
