name: CD

on: [push, pull_request, workflow_dispatch]

jobs:
  pypi:
    name: build and deploy to PyPI
    if: github.repository == 'ACCESS-NRI/ACCESS-MOPPeR' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install build dependencies
        run: python -m pip install build twine

      - name: Build distributions
        shell: bash -l {0}
        run: |
          git clean -xdf
          pyproject-build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true

  conda:
    name: build and deploy to conda (${{ matrix.os }})
    needs: pypi
    if: always() && needs.pypi.result == 'success'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.11]

    steps:
      - name: Debug matrix info
        run: |
          echo "Running on: ${{ matrix.os }}"
          echo "Python version: ${{ matrix.python-version }}"
          echo "Runner OS: ${{ runner.os }}"

      - name: Checkout source
        uses: actions/checkout@v5

      - name: Wait for PyPI propagation
        run: |
          echo "Waiting for PyPI package to be downloadable..."
          PACKAGE_NAME="access_mopper"
          VERSION=$(python -c "import versioneer; print(versioneer.get_version())")
          VERSION=${VERSION#v}
          echo "Looking for package: ${PACKAGE_NAME}==${VERSION}"

          # Wait up to 15 minutes for the files to be downloadable
          for i in {1..90}; do
            echo "Attempt $i/90: Trying to download wheel and sdist..."
            rm -rf /tmp/pypi_check_download && mkdir -p /tmp/pypi_check_download
            # Try to download both wheel and sdist
            pip download --no-deps --dest /tmp/pypi_check_download ${PACKAGE_NAME}==${VERSION} >/dev/null 2>&1
            WHEEL=$(ls /tmp/pypi_check_download/*.whl 2>/dev/null | head -1)
            SDIST=$(ls /tmp/pypi_check_download/*.tar.gz 2>/dev/null | head -1)
            if [[ -n "$WHEEL" && -n "$SDIST" ]]; then
              echo "✅ Both wheel and sdist for ${PACKAGE_NAME}==${VERSION} are downloadable!"
              break
            fi
            if [ $i -eq 90 ]; then
              echo "❌ Could not download both wheel and sdist after 15 minutes"
              echo "Available files:"
              ls -l /tmp/pypi_check_download || echo "No files downloaded"
              exit 1
            fi
            echo "Files not yet downloadable, waiting 10 seconds..."
            sleep 10
          done

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          environment-file: .conda/environment.yml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Build and upload the conda package
        uses: ACCESS-NRI/action-build-and-upload-conda-packages@v2.0.1
        with:
          meta_yaml_dir: .conda
          upload: true
          user: accessnri
          label: main
          token: ${{ secrets.anaconda_token }}
